-- Promold — catch-up from 0026
-- GENERATED by scripts/build-update.sh. Do not edit.
--
-- Paste into the Supabase SQL editor and run, on a database that is
-- already at 0026.
--
-- Safe to run more than once: this bundle only replaces functions,
-- policies and grants. Nothing in it creates a table or a type.
--
-- Contains, in order:
--   0027_price_write_guard.sql
--   0028_crew_lead_sees_price.sql
-- Generated from e413d3d

begin;

-- ===========================================================
-- 0027_price_write_guard.sql
-- ===========================================================
-- 0027 Price is manager information to WRITE as well as to read
--
-- 0018 revoked the price columns from the signed-in role so a crew lead could
-- not read them. It only ever revoked SELECT. Writing them stayed wide open,
-- and the row policy on a draft change order did not pin its status, so:
--
--   a crew lead drafts a change order (which is his job),
--   sets amount = 50000 (a column he cannot read),
--   sets status = 'approved' (a decision that is not his),
--
-- and `job_contract_price()` — base price plus approved change orders — goes
-- up by fifty thousand. He never sees the number. The owner's margin moves.
--
-- Confirmed exploitable against the seed before this migration. Two holes,
-- fixed separately because either alone still leaves a way in.

-- ---------------------------------------------------------------------------
-- 1. A draft stays a draft
-- ---------------------------------------------------------------------------

-- The old policy checked who owned the row and not what they were turning it
-- into, so "update my own draft" included "approve my own draft".
drop policy if exists change_orders_own_draft on change_orders;
create policy change_orders_own_draft on change_orders for update
  using (created_by = auth_user_id() and status = 'draft')
  with check (
    created_by = auth_user_id()
    -- Moving off draft goes through present_change_order() and
    -- decide_change_order(), which check changeorder.manage.
    and status = 'draft'
  );

-- ---------------------------------------------------------------------------
-- 2. The price columns are not writable either
-- ---------------------------------------------------------------------------

-- The same shape as grant_columns_except() in 0018, for INSERT and UPDATE.
-- A column-level revoke cannot override a table-level grant, so the table
-- grant is dropped and every other column is granted back.
create or replace function grant_writes_except(p_table text, p_exclude text[])
returns void
language plpgsql
as $fn$
declare v_cols text;
begin
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    return;
  end if;

  execute format('revoke insert, update on %I from authenticated', p_table);

  select string_agg(quote_ident(column_name), ', ' order by ordinal_position)
    into v_cols
    from information_schema.columns
   where table_schema = 'public'
     and table_name = p_table
     and not (column_name = any (p_exclude));

  execute format('grant insert (%s), update (%s) on %I to authenticated',
                 v_cols, v_cols, p_table);
end;
$fn$;

comment on function grant_writes_except(text, text[]) is
  'Drops the table-level insert/update grant and re-grants every column but '
  'the excluded ones. Adding a column to a table this was run on means '
  'running it again, exactly like grant_columns_except().';

select grant_writes_except('jobs', array['quoted_price']);
select grant_writes_except('change_orders', array['amount']);
select grant_writes_except('profiles', array['cost_rate']);

-- ---------------------------------------------------------------------------
-- 3. The legitimate ways to write a price
-- ---------------------------------------------------------------------------

-- create_job() already carries a price and is definer, so booking work is
-- unaffected. Editing one needs its own door now.
create or replace function set_job_price(p_job_id uuid, p_quoted_price numeric)
returns numeric
language plpgsql
security definer
set search_path = public
as $fn$
declare v_old numeric;
begin
  if not has_permission('job.edit') then
    raise exception 'Not permitted: changing a job needs job.edit'
      using errcode = '42501';
  end if;
  -- Deliberately both flags: someone who cannot see the price has no business
  -- setting it, and could not tell you what they had changed it from.
  if not has_permission('price.view') then
    raise exception 'Not permitted: setting a price needs price.view'
      using errcode = '42501';
  end if;
  if p_quoted_price is not null and p_quoted_price < 0 then
    raise exception 'A price cannot be negative' using errcode = '22023';
  end if;

  select quoted_price into v_old from jobs
   where id = p_job_id and org_id = auth_org_id() and deleted_at is null;
  if not found then
    raise exception 'No such job' using errcode = '02000';
  end if;

  update jobs set quoted_price = p_quoted_price where id = p_job_id;
  return v_old;
end;
$fn$;

comment on function set_job_price(uuid, numeric) is
  'The only way a client sets a quoted price. Needs job.edit AND price.view; '
  'the column itself is no longer writable by the signed-in role.';

-- Drafting is the crew's; pricing is not. This exists so the field app can
-- raise one without touching the amount column at all.
create or replace function create_change_order(
  p_job_id uuid,
  p_title text,
  p_description text default null,
  p_added_hours numeric default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_org uuid := auth_org_id();
  v_id uuid;
begin
  if not has_permission('changeorder.draft') then
    raise exception 'Not permitted: raising a change order needs changeorder.draft'
      using errcode = '42501';
  end if;
  if p_title is null or btrim(p_title) = '' then
    raise exception 'Say what was found' using errcode = '22023';
  end if;
  if not can_see_job(p_job_id) then
    raise exception 'That is not your job' using errcode = '42501';
  end if;

  insert into change_orders (
    org_id, job_id, title, description, added_hours, status, created_by
  ) values (
    v_org, p_job_id, btrim(p_title),
    nullif(btrim(coalesce(p_description, '')), ''),
    p_added_hours, 'draft', auth_user_id()
  )
  returning id into v_id;

  -- Returns the id only. The row carries a price column the caller may well
  -- not be allowed to read.
  return v_id;
end;
$fn$;

comment on function create_change_order(uuid, text, text, numeric) is
  'Raises a draft change order with no price on it. The person who opens a '
  'wall and finds rot is the person who knows; pricing it is the manager''s.';

-- ===========================================================
-- 0028_crew_lead_sees_price.sql
-- ===========================================================
-- 0028 A crew lead sees what the job is worth
--
-- The crew lead is the person standing in the basement when the wall comes
-- off and there is twice as much rot behind it as anybody quoted for. Until
-- now he could write that up but not see the number it was being measured
-- against, so "this is bigger than the job" was a feeling rather than a
-- figure. Giving him the contract price makes the report he sends the office
-- worth acting on: not "there's more here", but "there's more here and we
-- quoted 8,600 for it".
--
-- Reading a price and moving one are different things, and after 0027 they
-- are enforced differently. Nothing here lets him move it:
--
--   * `jobs.quoted_price` and `change_orders.amount` are not writable by the
--     signed-in role at all — 0027 dropped the table grant and re-granted
--     every other column. No permission flag brings that back.
--   * `set_job_price()` needs job.edit AND price.view. A crew lead has
--     neither job.edit nor any way to get it.
--   * `present_change_order()` and `decide_change_order()` need
--     changeorder.manage. He has changeorder.draft, which raises a draft with
--     no price on it, and the row policy pins it there.
--
-- Three things price.view deliberately does NOT open, because they are
-- separate flags and stay that way:
--
--   * `costing.view` — what the job cost us, and the margin. Still manager
--     and owner only. He sees the price, not the profit.
--   * `user.view_cost_rates` — what his colleagues are paid. Owner only.
--   * The technician role. This is the lead's job, not the whole crew's.

create or replace function provision_org_roles(p_org_id uuid)
returns void
language plpgsql
as $$
begin
  insert into roles (org_id, key, name, is_system, permissions) values
  (p_org_id, 'owner', 'Owner', true, jsonb_build_object(
    'job.view_all', true, 'job.edit', true, 'job.assign', true, 'job.accept', true,
    'job.complete', true, 'job.review', true, 'job.close', true, 'job.manage_templates', true,
    'reschedule.decide', true, 'customer.manage', true,
    'changeorder.draft', true, 'changeorder.manage', true,
    'inventory.manage', true, 'inventory.log_usage', true, 'inventory.transfer', true,
    'inventory.adjust', true,
    'purchase.approve', true, 'purchase.approve_unlimited', true,
    'purchase.view_all', true, 'purchase.view_history', true,
    'vehicle.manage', true, 'mileage.view_all', true, 'mileage.edit_all', true,
    'equipment.manage', true, 'equipment.place', true, 'equipment.rental_manage', true,
    'time.view_all', true, 'time.log_others', true, 'time.edit_all', true,
    'timeoff.manage', true, 'user.manage', true, 'user.view_cost_rates', true,
    'role.manage', true, 'org.manage_settings', true, 'audit.view', true,
    'data.restore', true,
    'price.view', true, 'costing.view', true, 'export.run', true
  )),

  (p_org_id, 'manager', 'Manager', true, jsonb_build_object(
    'job.view_all', true, 'job.edit', true, 'job.assign', true, 'job.accept', true,
    'job.complete', true, 'job.review', true, 'job.manage_templates', true,
    'reschedule.decide', true, 'customer.manage', true,
    'changeorder.draft', true, 'changeorder.manage', true,
    'inventory.manage', true, 'inventory.log_usage', true, 'inventory.transfer', true,
    'inventory.adjust', true,
    'purchase.approve', true, 'purchase.view_all', true, 'purchase.view_history', true,
    'vehicle.manage', true, 'mileage.view_all', true, 'mileage.edit_all', true,
    'equipment.manage', true, 'equipment.place', true, 'equipment.rental_manage', true,
    'time.view_all', true, 'time.log_others', true, 'time.edit_all', true,
    'timeoff.manage', true, 'user.manage', true, 'audit.view', true,
    'price.view', true, 'costing.view', true, 'export.run', true
  )),

  -- price.view, so he can tell the office the work has outgrown the quote.
  -- No costing.view: the price is not the margin.
  (p_org_id, 'crew_lead', 'Crew Lead', true, jsonb_build_object(
    'job.accept', true, 'job.complete', true,
    'changeorder.draft', true,
    'inventory.log_usage', true, 'inventory.transfer', true,
    'equipment.place', true,
    'time.log_others', true,
    'price.view', true
  )),

  -- Still no price. A technician is told what to do, not what it is worth.
  (p_org_id, 'technician', 'Technician', true, jsonb_build_object(
    'job.accept', true, 'job.complete', true,
    'changeorder.draft', true,
    'inventory.log_usage', true,
    'equipment.place', true
  )),

  -- Keeps the books, so needs the price but never the margin conversation.
  -- audit.view lets them read the trail; nothing here lets them change it.
  (p_org_id, 'bookkeeper', 'Bookkeeper', true, jsonb_build_object(
    'job.view_all', true,
    'purchase.view_all', true, 'purchase.view_history', true,
    'mileage.view_all', true, 'time.view_all', true,
    'audit.view', true, 'price.view', true, 'costing.view', true, 'export.run', true,
    'job.close', true
  ))
  on conflict (org_id, key) do nothing;
end;
$$;

-- Orgs that already exist. Only the system crew_lead role, and only where the
-- flag is not already set — an owner who turned it off by hand meant it.
update roles
   set permissions = permissions || '{"price.view": true}'::jsonb
 where key = 'crew_lead'
   and is_system
   and coalesce((permissions ->> 'price.view')::boolean, false) = false;


-- ===========================================================
-- Did it land?
-- ===========================================================
-- Printed by the same transaction that applied it, so there is no
-- second round trip to find out whether it worked.
select 'Applied' as result,
  (select count(*) from pg_proc where proname = 'set_job_price') > 0 as price_guard_0027,
  (select count(*) from information_schema.tables
    where table_schema = 'public') as tables,
  (select count(*) from pg_policies where schemaname = 'public') as policies;

commit;
