-- Promold — catch-up from 0021
-- GENERATED by scripts/build-update.sh. Do not edit.
--
-- Run this ONCE, in the Supabase SQL editor, on a database that is
-- already at 0021. It is not safe to run twice: it creates tables
-- and types, and the second run will stop on the first one that
-- already exists. That is deliberate — stopping is better than half
-- applying.
--
-- Contains, in order:
--   0022_admin_mode.sql
--   0023_job_authoring.sql
--   0024_decisions.sql
--   0025_consumables.sql
--   0026_purchasing.sql
-- Generated from ea5e2da

begin;

-- ===========================================================
-- 0022_admin_mode.sql
-- ===========================================================
-- 0022 Admin mode: the audit trail, record history, and getting a deleted
--      record back
--
-- Nothing in this app hard-deletes, which is only half a promise: until now
-- there was no way to see what had been deleted or to put it back. This
-- migration finishes the job.
--
-- Three rules live here, and they live here rather than in the admin screen:
--
--   1. A delete is refused while live children still point at the row. You
--      cannot delete a customer out from under its sites.
--   2. A restore is refused while the parent is still deleted. Putting a job
--      back under a deleted site would produce a row nobody can reach.
--   3. Restoring is its own permission, separate from deleting. Whoever can
--      remove a job is not automatically the person who decides it comes back.

-- ---------------------------------------------------------------------------
-- Finish the soft-delete columns
-- ---------------------------------------------------------------------------

alter table job_photos   add column if not exists delete_reason text;
alter table job_comments add column if not exists deleted_by uuid references profiles(id);
alter table job_comments add column if not exists delete_reason text;

-- The three registers with money attached. is_active already says "retired"
-- or "off the road"; deleted_at says "this should not have been created", and
-- conflating the two loses the difference.
alter table equipment       add column if not exists deleted_at timestamptz;
alter table equipment       add column if not exists deleted_by uuid references profiles(id);
alter table equipment       add column if not exists delete_reason text;
alter table vehicles        add column if not exists deleted_at timestamptz;
alter table vehicles        add column if not exists deleted_by uuid references profiles(id);
alter table vehicles        add column if not exists delete_reason text;
alter table inventory_items add column if not exists deleted_at timestamptz;
alter table inventory_items add column if not exists deleted_by uuid references profiles(id);
alter table inventory_items add column if not exists delete_reason text;

create index if not exists equipment_live on equipment (org_id) where deleted_at is null;
create index if not exists vehicles_live on vehicles (org_id) where deleted_at is null;
create index if not exists inventory_items_live on inventory_items (org_id) where deleted_at is null;

-- ---------------------------------------------------------------------------
-- A deleted row stops being ordinary data
--
-- Filtering in the client would leave the row one forgotten `.is('deleted_at',
-- null)` away from reappearing on a board. The select policy drops it instead,
-- and only audit.view — the flag admin mode itself runs on — sees it again.
-- ---------------------------------------------------------------------------

drop policy if exists jobs_select on jobs;
create policy jobs_select on jobs for select
  using (
    org_id = auth_org_id() and can_see_job(id)
    and (deleted_at is null or has_permission('audit.view'))
  );

drop policy if exists customers_select on customers;
create policy customers_select on customers for select
  using (
    org_id = auth_org_id()
    and (deleted_at is null or has_permission('audit.view'))
  );

drop policy if exists sites_select on sites;
create policy sites_select on sites for select
  using (
    org_id = auth_org_id()
    and (deleted_at is null or has_permission('audit.view'))
  );

drop policy if exists equipment_select on equipment;
create policy equipment_select on equipment for select
  using (
    org_id = auth_org_id()
    and (deleted_at is null or has_permission('audit.view'))
  );

drop policy if exists vehicles_select on vehicles;
create policy vehicles_select on vehicles for select
  using (
    org_id = auth_org_id()
    and (deleted_at is null or has_permission('audit.view'))
  );

drop policy if exists inventory_items_select on inventory_items;
create policy inventory_items_select on inventory_items for select
  using (
    org_id = auth_org_id()
    and (deleted_at is null or has_permission('audit.view'))
  );

-- ---------------------------------------------------------------------------
-- What can be deleted, and what hangs off what
--
-- A registry rather than a CASE statement in four functions. Adding a table to
-- the recycle bin is one insert, and the delete guard, the restore guard and
-- the admin screen all pick it up at once.
-- ---------------------------------------------------------------------------

create table deletable_tables (
  table_name text primary key,
  label text not null,
  -- The column that reads as this row's name in a list.
  title_column text not null,
  -- A short code shown beside it, where the table has one.
  ref_column text,
  -- The flag that lets someone delete one. Restoring is data.restore for all
  -- of them, on purpose.
  write_permission text not null,
  -- The row this one cannot outlive.
  parent_table text references deletable_tables(table_name),
  parent_fk text,
  sort int not null default 100,
  constraint deletable_parent_complete check (
    (parent_table is null and parent_fk is null) or
    (parent_table is not null and parent_fk is not null)
  )
);

comment on table deletable_tables is
  'Schema metadata, not org data: which tables soft-delete, how to name a row '
  'and which parent it depends on. Read by soft_delete_record(), '
  'restore_record() and deleted_records().';

insert into deletable_tables
  (table_name, label, title_column, ref_column, write_permission, parent_table, parent_fk, sort)
values
  ('customers',       'Customer',   'name',    null,        'customer.manage',  null,        null,          10),
  ('sites',           'Site',       'label',   null,        'customer.manage',  'customers', 'customer_id', 20),
  ('jobs',            'Job',        'title',   'job_number','job.edit',         'sites',     'site_id',     30),
  ('job_photos',      'Job photo',  'caption', null,        'job.edit',         'jobs',      'job_id',      40),
  ('job_comments',    'Job note',   'body',    null,        'job.edit',         'jobs',      'job_id',      50),
  ('equipment',       'Equipment',  'name',    'asset_tag', 'equipment.manage', null,        null,          60),
  ('vehicles',        'Vehicle',    'name',    'plate',     'vehicle.manage',   null,        null,          70),
  ('inventory_items', 'Stock item', 'name',    'sku',       'inventory.manage', null,        null,          80);

select enable_rls('deletable_tables');

-- Readable by anyone signed in; writable by nobody. Changing the recycle bin's
-- shape is a migration, not an afternoon.
create policy deletable_tables_select on deletable_tables for select using (true);

-- ---------------------------------------------------------------------------
-- Deleting
-- ---------------------------------------------------------------------------

create or replace function soft_delete_record(
  p_table text,
  p_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_org uuid := auth_org_id();
  v_me uuid := auth_user_id();
  v_meta deletable_tables;
  v_child deletable_tables;
  v_count int;
  v_blocked text[] := '{}';
  v_title text;
  v_live int;
begin
  select * into v_meta from deletable_tables where table_name = p_table;
  if not found then
    raise exception 'Not something this app deletes: %', p_table
      using errcode = '22023';
  end if;

  if not has_permission(v_meta.write_permission) then
    raise exception 'Not permitted: deleting a % needs %',
      lower(v_meta.label), v_meta.write_permission
      using errcode = '42501';
  end if;

  -- A delete with no reason is the one nobody can explain six months later.
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'Say why this % is being deleted', lower(v_meta.label)
      using errcode = '22023';
  end if;

  execute format(
    'select count(*), max(%I::text) from %I where id = $1 and org_id = $2 and deleted_at is null',
    v_meta.title_column, p_table)
    into v_live, v_title using p_id, v_org;

  if v_live = 0 then
    raise exception 'No % of that id is live here', lower(v_meta.label)
      using errcode = '02000';
  end if;

  -- Rule 1: live children keep the parent alive.
  for v_child in
    select * from deletable_tables where parent_table = p_table order by sort
  loop
    execute format(
      'select count(*) from %I where %I = $1 and org_id = $2 and deleted_at is null',
      v_child.table_name, v_child.parent_fk)
      into v_count using p_id, v_org;
    if v_count > 0 then
      v_blocked := array_append(
        v_blocked,
        v_count::text || ' ' || lower(v_child.label) || case when v_count = 1 then '' else 's' end);
    end if;
  end loop;

  if array_length(v_blocked, 1) > 0 then
    raise exception 'This % still has %. Deal with those first.',
      lower(v_meta.label), array_to_string(v_blocked, ' and ')
      using errcode = '23503';
  end if;

  execute format(
    'update %I set deleted_at = now(), deleted_by = $1, delete_reason = $2
      where id = $3 and org_id = $4 and deleted_at is null', p_table)
    using v_me, btrim(p_reason), p_id, v_org;

  insert into audit_log (org_id, table_name, record_id, actor_id, action, diff)
  values (v_org, p_table, p_id, v_me, 'soft_delete',
          jsonb_build_object('title', v_title, 'reason', btrim(p_reason)));

  return jsonb_build_object(
    'table', p_table, 'label', v_meta.label, 'id', p_id, 'title', v_title);
end;
$fn$;

comment on function soft_delete_record(text, uuid, text) is
  'Soft-deletes one row, gated on that table''s own write permission. Refuses '
  'while live children point at it, and refuses without a reason.';

-- ---------------------------------------------------------------------------
-- Getting it back
-- ---------------------------------------------------------------------------

create or replace function restore_record(
  p_table text,
  p_id uuid,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_org uuid := auth_org_id();
  v_me uuid := auth_user_id();
  v_meta deletable_tables;
  v_parent deletable_tables;
  v_parent_name text;
  v_title text;
  v_gone int;
begin
  select * into v_meta from deletable_tables where table_name = p_table;
  if not found then
    raise exception 'Not something this app deletes: %', p_table
      using errcode = '22023';
  end if;

  -- Deliberately not the delete permission. Putting a record back into live
  -- data is its own decision.
  if not has_permission('data.restore') then
    raise exception 'Not permitted: restoring a record needs data.restore'
      using errcode = '42501';
  end if;

  execute format(
    'select count(*), max(%I::text) from %I where id = $1 and org_id = $2 and deleted_at is not null',
    v_meta.title_column, p_table)
    into v_gone, v_title using p_id, v_org;

  if v_gone = 0 then
    raise exception 'No deleted % of that id here', lower(v_meta.label)
      using errcode = '02000';
  end if;

  -- Rule 2: a row cannot come back under a parent that is still deleted.
  if v_meta.parent_table is not null then
    select * into v_parent from deletable_tables where table_name = v_meta.parent_table;
    execute format(
      'select coalesce(nullif(p.%I::text, %L), %L)
         from %I c join %I p on p.id = c.%I
        where c.id = $1 and c.org_id = $2 and p.deleted_at is not null',
      v_parent.title_column, '', '(no name)',
      p_table, v_meta.parent_table, v_meta.parent_fk)
      into v_parent_name using p_id, v_org;

    if v_parent_name is not null then
      raise exception 'Restore the % first: % is deleted too',
        lower(v_parent.label), v_parent_name
        using errcode = '23503';
    end if;
  end if;

  execute format(
    'update %I set deleted_at = null, deleted_by = null, delete_reason = null
      where id = $1 and org_id = $2 and deleted_at is not null', p_table)
    using p_id, v_org;

  insert into audit_log (org_id, table_name, record_id, actor_id, action, diff)
  values (v_org, p_table, p_id, v_me, 'restore',
          jsonb_build_object('title', v_title, 'reason', nullif(btrim(coalesce(p_reason, '')), '')));

  return jsonb_build_object(
    'table', p_table, 'label', v_meta.label, 'id', p_id, 'title', v_title);
end;
$fn$;

comment on function restore_record(text, uuid, text) is
  'Clears the soft delete, gated on data.restore. Refuses while the parent row '
  'is still deleted, which would otherwise produce an unreachable record.';

-- ---------------------------------------------------------------------------
-- The recycle bin
--
-- One list across every table that soft-deletes, newest first, each row
-- carrying what stands between it and being restored.
-- ---------------------------------------------------------------------------

create or replace function deleted_records(
  p_table text default null,
  p_limit int default 200
)
returns table (
  table_name text,
  label text,
  record_id uuid,
  title text,
  ref text,
  deleted_at timestamptz,
  deleted_by uuid,
  deleted_by_name text,
  delete_reason text,
  blocked_by text
)
language plpgsql
stable
security definer
set search_path = public
as $fn$
declare
  r record;
  v_sql text := '';
  v_org uuid := auth_org_id();
begin
  if not has_permission('audit.view') then
    raise exception 'Not permitted: seeing deleted records needs audit.view'
      using errcode = '42501';
  end if;

  for r in
    select d.*, p.label as parent_label, p.title_column as parent_title
    from deletable_tables d
    left join deletable_tables p on p.table_name = d.parent_table
    where (p_table is null or d.table_name = p_table)
    order by d.sort
  loop
    v_sql := v_sql
      || case when v_sql = '' then '' else ' union all ' end
      || format($q$
           select %L::text as table_name,
                  %L::text as label,
                  t.id as record_id,
                  nullif(t.%I::text, '') as title,
                  %s as ref,
                  t.deleted_at,
                  t.deleted_by,
                  pr.full_name as deleted_by_name,
                  t.delete_reason,
                  %s as blocked_by
             from %I t
             left join profiles pr on pr.id = t.deleted_by
            where t.org_id = $1 and t.deleted_at is not null
         $q$,
         r.table_name,
         r.label,
         r.title_column,
         case when r.ref_column is null then 'null::text'
              else format('t.%I::text', r.ref_column) end,
         case when r.parent_table is null then 'null::text'
              else format(
                $p$(select %L || ' - ' || coalesce(nullif(pp.%I::text, ''), '(no name)')
                      from %I pp
                     where pp.id = t.%I and pp.deleted_at is not null)$p$,
                r.parent_label, r.parent_title, r.parent_table, r.parent_fk)
         end,
         r.table_name);
  end loop;

  if v_sql = '' then return; end if;

  return query execute
    'select * from (' || v_sql || ') z order by z.deleted_at desc limit $2'
    using v_org, p_limit;
end;
$fn$;

comment on function deleted_records(text, int) is
  'Everything soft-deleted in this org, newest first, with the parent that '
  'blocks a restore where there is one. Gated on audit.view.';

-- ---------------------------------------------------------------------------
-- History
-- ---------------------------------------------------------------------------

-- What has happened to one record, ever.
create or replace function record_history(
  p_table text,
  p_id uuid,
  p_limit int default 200
)
returns table (
  id bigint,
  at timestamptz,
  action text,
  actor_id uuid,
  actor_name text,
  fields text[],
  diff jsonb
)
language plpgsql
stable
security definer
set search_path = public
as $fn$
begin
  if not has_permission('audit.view') then
    raise exception 'Not permitted: record history needs audit.view'
      using errcode = '42501';
  end if;
  return query
  select
    a.id,
    a.at,
    a.action,
    a.actor_id,
    coalesce(p.full_name, 'System') as actor_name,
    case when a.action = 'update'
      then array(select k from jsonb_object_keys(coalesce(a.diff, '{}'::jsonb)) k order by k)
      else '{}'::text[] end as fields,
    a.diff
  from audit_log a
  left join profiles p on p.id = a.actor_id
  where a.org_id = auth_org_id()
    and a.table_name = p_table
    and a.record_id = p_id
  order by a.at desc, a.id desc
  limit p_limit;
end;
$fn$;

comment on function record_history(text, uuid, int) is
  'The full trail for one record: who changed what, when. Gated on audit.view.';

-- Everything, filtered and paged. p_before_id is the cursor: pass the last id
-- you were given to get the next page, rather than an offset that shifts under
-- you as new rows land.
create or replace function audit_feed(
  p_table text default null,
  p_actor uuid default null,
  p_action text default null,
  p_since timestamptz default null,
  p_before_id bigint default null,
  p_limit int default 100
)
returns table (
  id bigint,
  at timestamptz,
  table_name text,
  label text,
  record_id uuid,
  action text,
  actor_id uuid,
  actor_name text,
  fields text[],
  diff jsonb
)
language plpgsql
stable
security definer
set search_path = public
as $fn$
begin
  if not has_permission('audit.view') then
    raise exception 'Not permitted: the audit trail needs audit.view'
      using errcode = '42501';
  end if;
  return query
  select
    a.id,
    a.at,
    a.table_name,
    coalesce(d.label, a.table_name) as label,
    a.record_id,
    a.action,
    a.actor_id,
    coalesce(p.full_name, 'System') as actor_name,
    case when a.action = 'update'
      then array(select k from jsonb_object_keys(coalesce(a.diff, '{}'::jsonb)) k order by k)
      else '{}'::text[] end as fields,
    a.diff
  from audit_log a
  left join profiles p on p.id = a.actor_id
  left join deletable_tables d on d.table_name = a.table_name
  where a.org_id = auth_org_id()
    and (p_table is null or a.table_name = p_table)
    and (p_actor is null or a.actor_id = p_actor)
    and (p_action is null or a.action = p_action)
    and (p_since is null or a.at >= p_since)
    and (p_before_id is null or a.id < p_before_id)
  order by a.id desc
  limit least(coalesce(p_limit, 100), 500);
end;
$fn$;

comment on function audit_feed(text, uuid, text, timestamptz, bigint, int) is
  'The org''s audit trail, filtered and cursor-paged on id. Gated on audit.view.';

-- What the filter dropdown offers, so it lists only what has actually happened.
create or replace function audit_tables()
returns table (table_name text, label text, entries bigint)
language plpgsql
stable
security definer
set search_path = public
as $fn$
begin
  if not has_permission('audit.view') then
    raise exception 'Not permitted: the audit trail needs audit.view'
      using errcode = '42501';
  end if;
  return query
  select a.table_name,
         coalesce(d.label, a.table_name) as label,
         count(*) as entries
  from audit_log a
  left join deletable_tables d on d.table_name = a.table_name
  where a.org_id = auth_org_id()
  group by a.table_name, d.label
  order by 2;
end;
$fn$;

-- ---------------------------------------------------------------------------
-- Audit the rest of what an owner edits
--
-- The trail is only worth opening if the things people actually change are in
-- it. Customers, sites, the day a job runs, approved time off and the two
-- registers were all missing.
-- ---------------------------------------------------------------------------

select attach_audit('customers');
select attach_audit('sites');
select attach_audit('job_visits');
select attach_audit('time_off');
select attach_audit('vehicles');
select attach_audit('equipment');

-- ---------------------------------------------------------------------------
-- data.restore
--
-- Separate from every delete permission on purpose. A manager who can delete a
-- customer record should not be the one who quietly puts it back.
-- ---------------------------------------------------------------------------

create or replace function provision_org_roles(p_org_id uuid)
returns void
language plpgsql
as $$
begin
  insert into roles (org_id, key, name, is_system, permissions) values
  (p_org_id, 'owner', 'Owner', true, jsonb_build_object(
    'job.view_all', true, 'job.edit', true, 'job.assign', true, 'job.accept', true,
    'job.complete', true, 'job.review', true, 'job.close', true, 'job.manage_templates', true,
    'reschedule.decide', true, 'customer.manage', true,
    'changeorder.draft', true, 'changeorder.manage', true,
    'inventory.manage', true, 'inventory.log_usage', true, 'inventory.transfer', true,
    'inventory.adjust', true,
    'purchase.approve', true, 'purchase.approve_unlimited', true,
    'purchase.view_all', true, 'purchase.view_history', true,
    'vehicle.manage', true, 'mileage.view_all', true, 'mileage.edit_all', true,
    'equipment.manage', true, 'equipment.place', true, 'equipment.rental_manage', true,
    'time.view_all', true, 'time.log_others', true, 'time.edit_all', true,
    'timeoff.manage', true, 'user.manage', true, 'user.view_cost_rates', true,
    'role.manage', true, 'org.manage_settings', true, 'audit.view', true,
    'data.restore', true,
    'price.view', true, 'costing.view', true, 'export.run', true
  )),

  (p_org_id, 'manager', 'Manager', true, jsonb_build_object(
    'job.view_all', true, 'job.edit', true, 'job.assign', true, 'job.accept', true,
    'job.complete', true, 'job.review', true, 'job.manage_templates', true,
    'reschedule.decide', true, 'customer.manage', true,
    'changeorder.draft', true, 'changeorder.manage', true,
    'inventory.manage', true, 'inventory.log_usage', true, 'inventory.transfer', true,
    'inventory.adjust', true,
    'purchase.approve', true, 'purchase.view_all', true, 'purchase.view_history', true,
    'vehicle.manage', true, 'mileage.view_all', true, 'mileage.edit_all', true,
    'equipment.manage', true, 'equipment.place', true, 'equipment.rental_manage', true,
    'time.view_all', true, 'time.log_others', true, 'time.edit_all', true,
    'timeoff.manage', true, 'user.manage', true, 'audit.view', true,
    'price.view', true, 'costing.view', true, 'export.run', true
  )),

  -- No price.view: a crew lead runs the work, not the commercials.
  (p_org_id, 'crew_lead', 'Crew Lead', true, jsonb_build_object(
    'job.accept', true, 'job.complete', true,
    'changeorder.draft', true,
    'inventory.log_usage', true, 'inventory.transfer', true,
    'equipment.place', true,
    'time.log_others', true
  )),

  (p_org_id, 'technician', 'Technician', true, jsonb_build_object(
    'job.accept', true, 'job.complete', true,
    'changeorder.draft', true,
    'inventory.log_usage', true,
    'equipment.place', true
  )),

  -- Keeps the books, so needs the price but never the margin conversation.
  -- audit.view lets them read the trail; nothing here lets them change it.
  (p_org_id, 'bookkeeper', 'Bookkeeper', true, jsonb_build_object(
    'job.view_all', true,
    'purchase.view_all', true, 'purchase.view_history', true,
    'mileage.view_all', true, 'time.view_all', true,
    'audit.view', true, 'price.view', true, 'costing.view', true, 'export.run', true,
    'job.close', true
  ))
  on conflict (org_id, key) do nothing;
end;
$$;

-- Orgs that already exist get the flag too, or the owner locks themselves out
-- of the screen this migration is for.
update roles
   set permissions = permissions || jsonb_build_object('data.restore', true)
 where key = 'owner'
   and coalesce((permissions ->> 'data.restore')::boolean, false) = false;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'grant select on deletable_tables to authenticated';
  end if;
end $$;

-- ===========================================================
-- 0023_job_authoring.sql
-- ===========================================================
-- 0023 Creating and editing a job
--
-- Putting work on the calendar is three writes that have to agree: the job,
-- the work days behind it, and who is going. Doing that from a client leaves
-- half-made jobs behind whenever a tab closes at the wrong moment, and leaves
-- each client free to invent its own idea of what a valid job is.
--
-- So it is one function per intent, and the rules sit with the data:
--
--   * a site has to belong to the customer it is booked under;
--   * a multi-day job produces one visit per day, not one visit;
--   * nobody is assigned over approved time off, ever;
--   * a double booking is refused but can be overridden deliberately, because
--     sometimes two short jobs really do fit and only the manager knows.

-- ---------------------------------------------------------------------------
-- Work days
-- ---------------------------------------------------------------------------

-- Rebuilds the visits for a job from its scheduled range: one per calendar
-- day, each keeping the job's own start and end times. A one-day job gets
-- exactly one. Visits that already have work recorded against them are left
-- alone rather than silently replaced.
create or replace function rebuild_job_visits(p_job_id uuid)
returns int
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_job jobs;
  v_day date;
  v_last date;
  v_seq int := 0;
  v_start timestamptz;
  v_end timestamptz;
begin
  select * into v_job from jobs where id = p_job_id;
  if not found then
    raise exception 'No such job' using errcode = '02000';
  end if;
  if v_job.scheduled_start is null then
    return 0;
  end if;

  -- Anything already under way keeps its visit; re-cutting the days under a
  -- crew who are standing in the basement is not a scheduling change.
  delete from job_visits
   where job_id = p_job_id
     and status = 'scheduled'
     and not exists (select 1 from time_entries t where t.visit_id = job_visits.id);

  v_day := (v_job.scheduled_start at time zone 'UTC')::date;
  v_last := (coalesce(v_job.scheduled_end, v_job.scheduled_start) at time zone 'UTC')::date;

  while v_day <= v_last loop
    v_seq := v_seq + 1;

    -- Keep the job's clock times, moved onto this day.
    v_start := v_day + (v_job.scheduled_start at time zone 'UTC')::time;
    v_end := v_day + (coalesce(v_job.scheduled_end, v_job.scheduled_start + interval '4 hours')
                      at time zone 'UTC')::time;
    if v_end <= v_start then
      v_end := v_start + interval '4 hours';
    end if;

    insert into job_visits (org_id, job_id, seq, scheduled_start, scheduled_end)
    values (v_job.org_id, p_job_id, v_seq, v_start, v_end)
    on conflict (job_id, seq) do update
      set scheduled_start = excluded.scheduled_start,
          scheduled_end = excluded.scheduled_end;

    v_day := v_day + 1;
  end loop;

  -- A job that got shorter should not keep the days it no longer runs.
  delete from job_visits
   where job_id = p_job_id
     and seq > v_seq
     and status = 'scheduled'
     and not exists (select 1 from time_entries t where t.visit_id = job_visits.id);

  return v_seq;
end;
$fn$;

comment on function rebuild_job_visits(uuid) is
  'One visit per calendar day the job runs, keeping its clock times. Leaves '
  'visits that already have time logged against them.';

-- ---------------------------------------------------------------------------
-- Who is going
-- ---------------------------------------------------------------------------

create or replace function set_job_crew(
  p_job_id uuid,
  p_user_ids uuid[],
  p_force boolean default false
)
returns int
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_job jobs;
  v_user uuid;
  v_name text;
  v_conflicts text[];
  v_hard text[] := '{}';
  v_soft text[] := '{}';
  v_kept int := 0;
begin
  if not has_permission('job.assign') then
    raise exception 'Not permitted: assigning work needs job.assign'
      using errcode = '42501';
  end if;

  select * into v_job from jobs where id = p_job_id and org_id = auth_org_id()
    and deleted_at is null;
  if not found then
    raise exception 'No such job' using errcode = '02000';
  end if;
  if v_job.scheduled_start is null then
    raise exception 'Put the job on the calendar before putting people on it'
      using errcode = '22023';
  end if;

  -- Check everyone first and report together. Finding out about the second
  -- clash only after fixing the first is how a three-person crew takes three
  -- attempts to book.
  foreach v_user in array coalesce(p_user_ids, '{}'::uuid[]) loop
    select full_name into v_name from profiles
     where id = v_user and org_id = v_job.org_id and is_active;
    if v_name is null then
      raise exception 'That person is not on the staff list' using errcode = '23503';
    end if;

    v_conflicts := scheduling_conflicts(
      v_user, v_job.scheduled_start,
      coalesce(v_job.scheduled_end, v_job.scheduled_start), p_job_id);

    if v_conflicts is not null then
      -- Approved time off is not a judgement call: they are not there.
      if exists (select 1 from unnest(v_conflicts) c where c ilike '%time off%') then
        v_hard := array_append(v_hard, v_name || ': ' ||
          (select string_agg(c, '; ') from unnest(v_conflicts) c where c ilike '%time off%'));
      end if;
      if exists (select 1 from unnest(v_conflicts) c where c not ilike '%time off%') then
        v_soft := array_append(v_soft, v_name || ': ' ||
          (select string_agg(c, '; ') from unnest(v_conflicts) c where c not ilike '%time off%'));
      end if;
    end if;
  end loop;

  if array_length(v_hard, 1) > 0 then
    raise exception 'Approved time off. %', array_to_string(v_hard, ' / ')
      using errcode = '23514';
  end if;
  if array_length(v_soft, 1) > 0 and not p_force then
    raise exception 'Already booked. %', array_to_string(v_soft, ' / ')
      using errcode = '23505';
  end if;

  -- Anyone dropped from the crew loses their row; anyone kept keeps the
  -- acceptance they already gave, so adding a fourth person does not make the
  -- other three answer again.
  delete from job_assignments
   where job_id = p_job_id
     and not (user_id = any (coalesce(p_user_ids, '{}'::uuid[])));

  foreach v_user in array coalesce(p_user_ids, '{}'::uuid[]) loop
    insert into job_assignments (org_id, job_id, user_id, assigned_by)
    values (v_job.org_id, p_job_id, v_user, auth_user_id())
    on conflict (job_id, user_id, visit_id) do nothing;
  end loop;

  select count(*) into v_kept from job_assignments where job_id = p_job_id;

  -- Having people on it is what "assigned" means, so keep the status honest
  -- in both directions.
  if v_kept > 0 and v_job.status = 'scheduled' then
    perform transition_job(p_job_id, 'assigned', 'Crew set');
  elsif v_kept = 0 and v_job.status = 'assigned' then
    perform transition_job(p_job_id, 'scheduled', 'Crew cleared');
  end if;

  return v_kept;
end;
$fn$;

comment on function set_job_crew(uuid, uuid[], boolean) is
  'Replaces a job''s crew. Refuses approved time off outright; refuses a '
  'double booking unless p_force. Keeps the acceptance of anyone already on.';

-- ---------------------------------------------------------------------------
-- Creating
-- ---------------------------------------------------------------------------

create or replace function create_job(
  p_customer_id uuid,
  p_site_id uuid,
  p_title text,
  p_scheduled_start timestamptz,
  p_scheduled_end timestamptz default null,
  p_description text default null,
  p_template_id uuid default null,
  p_priority job_priority default 'normal',
  p_quoted_price numeric default null,
  p_crew uuid[] default '{}'
)
returns jobs
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_org uuid := auth_org_id();
  v_job jobs;
  v_ok int;
begin
  if not has_permission('job.edit') then
    raise exception 'Not permitted: creating a job needs job.edit'
      using errcode = '42501';
  end if;

  if p_title is null or btrim(p_title) = '' then
    raise exception 'A job needs a title' using errcode = '22023';
  end if;
  if p_scheduled_start is null then
    raise exception 'A job needs a day' using errcode = '22023';
  end if;
  if p_scheduled_end is not null and p_scheduled_end < p_scheduled_start then
    raise exception 'The job ends before it starts' using errcode = '22023';
  end if;

  -- A site under the wrong customer is the mistake that produces a job
  -- history nobody can trust, so it is refused rather than tidied later.
  select count(*) into v_ok from sites
   where id = p_site_id and customer_id = p_customer_id and org_id = v_org
     and deleted_at is null;
  if v_ok = 0 then
    raise exception 'That site does not belong to that customer'
      using errcode = '23503';
  end if;

  insert into jobs (
    org_id, customer_id, site_id, template_id, title, description,
    priority, scheduled_start, scheduled_end, quoted_price, created_by
  ) values (
    v_org, p_customer_id, p_site_id, p_template_id, btrim(p_title),
    nullif(btrim(coalesce(p_description, '')), ''),
    coalesce(p_priority, 'normal'), p_scheduled_start, p_scheduled_end,
    p_quoted_price, auth_user_id()
  )
  returning * into v_job;

  perform rebuild_job_visits(v_job.id);

  -- A job created on the calendar is scheduled, not a draft: the draft state
  -- is for work being quoted, and this screen is for work being booked.
  perform transition_job(v_job.id, 'scheduled', 'Created on the calendar');

  if array_length(p_crew, 1) > 0 then
    perform set_job_crew(v_job.id, p_crew);
  end if;

  select * into v_job from jobs where id = v_job.id;
  return v_job;
end;
$fn$;

comment on function create_job(uuid, uuid, text, timestamptz, timestamptz, text, uuid, job_priority, numeric, uuid[]) is
  'Creates a job, cuts its work days, schedules it and optionally assigns a '
  'crew — in one transaction, so a half-made job cannot be left behind.';

-- ---------------------------------------------------------------------------
-- Editing
-- ---------------------------------------------------------------------------

-- Moving a job is not the same edit as renaming one: the work days have to
-- follow, and everyone who agreed to the old time has to agree again.
create or replace function reschedule_job(
  p_job_id uuid,
  p_scheduled_start timestamptz,
  p_scheduled_end timestamptz default null,
  p_reason text default null
)
returns jobs
language plpgsql
security definer
set search_path = public
as $fn$
declare v_job jobs;
begin
  if not has_permission('job.edit') then
    raise exception 'Not permitted: moving a job needs job.edit'
      using errcode = '42501';
  end if;

  select * into v_job from jobs
   where id = p_job_id and org_id = auth_org_id() and deleted_at is null;
  if not found then
    raise exception 'No such job' using errcode = '02000';
  end if;
  if p_scheduled_end is not null and p_scheduled_end < p_scheduled_start then
    raise exception 'The job ends before it starts' using errcode = '22023';
  end if;

  update jobs
     set scheduled_start = p_scheduled_start,
         scheduled_end = p_scheduled_end
   where id = p_job_id;

  perform rebuild_job_visits(p_job_id);

  -- They agreed to a Tuesday. This is a Thursday.
  if p_scheduled_start is distinct from v_job.scheduled_start
     or p_scheduled_end is distinct from v_job.scheduled_end then
    update job_assignments
       set acceptance_status = 'pending', responded_at = null
     where job_id = p_job_id
       and acceptance_status <> 'pending';

    insert into job_status_history (org_id, job_id, from_status, to_status, changed_by, note)
    values (v_job.org_id, p_job_id, v_job.status, v_job.status, auth_user_id(),
            coalesce(nullif(btrim(coalesce(p_reason, '')), ''), 'Rescheduled'));
  end if;

  select * into v_job from jobs where id = p_job_id;
  return v_job;
end;
$fn$;

comment on function reschedule_job(uuid, timestamptz, timestamptz, text) is
  'Moves a job, re-cuts its work days and resets everyone''s acceptance — '
  'they agreed to the old time, not this one.';

-- ===========================================================
-- 0024_decisions.sql
-- ===========================================================
-- 0024 Answering the crew
--
-- The field app lets a crew member ask to move a job and ask for time off.
-- Until now nothing could answer either: `decide_reschedule` existed but
-- moved a job without re-cutting its work days, and time off had no decision
-- function at all — only a raw update that could leave `decided_by` blank and
-- a decline with no reason.
--
-- A request nobody can answer is worse than no request: the crew learn the
-- app does not work and go back to phoning.

-- ---------------------------------------------------------------------------
-- Moving a job un-agrees it
-- ---------------------------------------------------------------------------

-- Accepting is agreeing to a time. Change the time and the agreement lapses,
-- which means the job is back to waiting on people rather than settled.
insert into job_transitions (from_status, to_status, required_permission, guard, enabled)
values ('accepted', 'assigned', 'job.assign', null, true)
on conflict (from_status, to_status) do update
  set required_permission = excluded.required_permission,
      enabled = true;

-- Used wherever a job's time changes. Resets every acceptance — not only the
-- person who asked, because the others agreed to the old time too — and steps
-- the status back if the job had been fully accepted.
create or replace function unaccept_job(p_job_id uuid, p_note text default null)
returns void
language plpgsql
security definer
set search_path = public
as $fn$
declare v_status job_status;
begin
  update job_assignments
     set acceptance_status = 'pending', responded_at = null
   where job_id = p_job_id
     and acceptance_status <> 'pending';

  select status into v_status from jobs where id = p_job_id;

  -- Only the office can put a job back to 'assigned'. Anyone else changing a
  -- time still un-agrees it; the status simply stays where it was rather than
  -- the whole decision failing on a permission check.
  if v_status = 'accepted' and has_permission('job.assign') then
    perform transition_job(p_job_id, 'assigned',
                           coalesce(p_note, 'Time changed — everyone re-accepts'));
  end if;
end;
$fn$;

comment on function unaccept_job(uuid, text) is
  'Resets every acceptance on a job and steps it back from accepted to '
  'assigned. Called wherever a job''s time changes.';

-- 0023 reset acceptance itself; route it through the shared rule instead, so
-- the status follows too.
create or replace function reschedule_job(
  p_job_id uuid,
  p_scheduled_start timestamptz,
  p_scheduled_end timestamptz default null,
  p_reason text default null
)
returns jobs
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_job jobs;
  v_moved boolean;
begin
  if not has_permission('job.edit') then
    raise exception 'Not permitted: moving a job needs job.edit'
      using errcode = '42501';
  end if;

  select * into v_job from jobs
   where id = p_job_id and org_id = auth_org_id() and deleted_at is null;
  if not found then
    raise exception 'No such job' using errcode = '02000';
  end if;
  if p_scheduled_end is not null and p_scheduled_end < p_scheduled_start then
    raise exception 'The job ends before it starts' using errcode = '22023';
  end if;

  v_moved := p_scheduled_start is distinct from v_job.scheduled_start
          or p_scheduled_end is distinct from v_job.scheduled_end;

  update jobs
     set scheduled_start = p_scheduled_start,
         scheduled_end = p_scheduled_end
   where id = p_job_id;

  perform rebuild_job_visits(p_job_id);

  if v_moved then
    perform unaccept_job(p_job_id, coalesce(nullif(btrim(coalesce(p_reason, '')), ''), 'Rescheduled'));

    insert into job_status_history (org_id, job_id, from_status, to_status, changed_by, note)
    values (v_job.org_id, p_job_id, v_job.status, v_job.status, auth_user_id(),
            coalesce(nullif(btrim(coalesce(p_reason, '')), ''), 'Rescheduled'));
  end if;

  select * into v_job from jobs where id = p_job_id;
  return v_job;
end;
$fn$;

-- ---------------------------------------------------------------------------
-- Deciding a reschedule request
-- ---------------------------------------------------------------------------

-- Replaces the 0012 version. Two things were wrong with it: approving moved
-- the job without re-cutting its work days, so a three-day job kept the old
-- three days on everyone's calendar; and it wrote `jobs.status` directly,
-- which is the one thing nothing in this schema is allowed to do.
--
-- It also now takes the new time from whoever is deciding. The crew member
-- knows Tuesday does not work; the office is the one who knows what else is
-- booked, so they pick the slot.
create or replace function decide_reschedule(
  p_request_id uuid,
  p_approve boolean,
  p_reason text default null,
  p_new_start timestamptz default null,
  p_new_end timestamptz default null
)
returns reschedule_requests
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_request reschedule_requests;
  v_start timestamptz;
  v_end timestamptz;
begin
  if not has_permission('reschedule.decide') then
    raise exception 'Not permitted: deciding this needs reschedule.decide'
      using errcode = '42501';
  end if;

  select * into v_request from reschedule_requests
   where id = p_request_id and org_id = auth_org_id()
   for update;
  if not found then
    raise exception 'No such request' using errcode = '02000';
  end if;
  if v_request.status <> 'pending' then
    raise exception 'That request was already %', v_request.status
      using errcode = '22023';
  end if;
  if not p_approve and (p_reason is null or btrim(p_reason) = '') then
    raise exception 'Say why, so they are not left guessing'
      using errcode = '22023';
  end if;

  -- The decider's time wins; the requester's proposal is the fallback.
  v_start := coalesce(p_new_start, v_request.proposed_start);
  v_end := coalesce(p_new_end, v_request.proposed_end);

  if p_approve and v_start is null then
    raise exception 'Approving needs a new time — they asked to move it, not to drop it'
      using errcode = '22023';
  end if;

  update reschedule_requests
     set status = case when p_approve then 'approved' else 'declined' end::reschedule_status,
         decided_by = auth_user_id(),
         decided_at = now(),
         decision_reason = nullif(btrim(coalesce(p_reason, '')), '')
   where id = p_request_id
   returning * into v_request;

  if p_approve then
    -- Goes through the same door the office uses, so the work days follow and
    -- everyone re-accepts.
    perform reschedule_job(v_request.job_id, v_start, v_end,
                           'Moved after a reschedule request');
  else
    -- Declined: the job stays where it is, and the person who asked still has
    -- to answer it.
    update job_assignments
       set acceptance_status = 'pending', responded_at = null
     where id = v_request.assignment_id;
  end if;

  return v_request;
end;
$fn$;

comment on function decide_reschedule(uuid, boolean, text, timestamptz, timestamptz) is
  'Approve with a new time, or decline with a reason. Approving moves the job '
  'through reschedule_job(), so the work days are re-cut and every acceptance '
  'resets.';

-- ---------------------------------------------------------------------------
-- Deciding time off
-- ---------------------------------------------------------------------------

-- The jobs someone is already booked on inside a window. Shown to the person
-- asking before they send it, and to whoever is deciding — the same list, so
-- neither side is surprised.
create or replace function time_off_clashes(p_request_id uuid)
returns table (
  job_id uuid,
  job_number text,
  title text,
  scheduled_start timestamptz,
  scheduled_end timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $fn$
declare v_req time_off;
begin
  select * into v_req from time_off
   where id = p_request_id and org_id = auth_org_id();
  if not found then
    return;
  end if;

  -- Their own request, or someone whose job it is to decide it.
  if v_req.user_id <> auth_user_id() and not has_permission('timeoff.manage') then
    raise exception 'Not permitted' using errcode = '42501';
  end if;

  return query
  select j.id, j.job_number, j.title, j.scheduled_start, j.scheduled_end
    from job_assignments a
    join jobs j on j.id = a.job_id
   where a.user_id = v_req.user_id
     and j.deleted_at is null
     and j.status not in ('cancelled', 'closed')
     and j.scheduled_start is not null
     and tstzrange(j.scheduled_start, coalesce(j.scheduled_end, j.scheduled_start), '[]')
         && tstzrange(v_req.starts_at, v_req.ends_at, '[]')
   order by j.scheduled_start;
end;
$fn$;

comment on function time_off_clashes(uuid) is
  'The jobs this person is already booked on inside the requested window. '
  'Same list for the requester and the decider.';

create or replace function decide_time_off(
  p_request_id uuid,
  p_approve boolean,
  p_reason text default null
)
returns time_off
language plpgsql
security definer
set search_path = public
as $fn$
declare v_req time_off;
begin
  if not has_permission('timeoff.manage') then
    raise exception 'Not permitted: deciding time off needs timeoff.manage'
      using errcode = '42501';
  end if;

  select * into v_req from time_off
   where id = p_request_id and org_id = auth_org_id()
   for update;
  if not found then
    raise exception 'No such request' using errcode = '02000';
  end if;
  if v_req.status <> 'requested' then
    raise exception 'That request was already %', v_req.status using errcode = '22023';
  end if;

  -- A decline with no reason is how people stop asking, and then stop telling
  -- you they will not be there.
  if not p_approve and (p_reason is null or btrim(p_reason) = '') then
    raise exception 'Say why. They read this on their phone.'
      using errcode = '22023';
  end if;

  -- Deliberately does NOT refuse over a booked job, and deliberately does not
  -- move that job either. Approving records that the person will not be
  -- there; reassigning someone else's work is a decision, not a side effect.
  -- From this moment the scheduling conflict check refuses new bookings for
  -- those dates.
  update time_off
     set status = case when p_approve then 'approved' else 'declined' end::time_off_status,
         decided_by = auth_user_id(),
         decided_at = now(),
         decision_reason = nullif(btrim(coalesce(p_reason, '')), '')
   where id = p_request_id
   returning * into v_req;

  return v_req;
end;
$fn$;

comment on function decide_time_off(uuid, boolean, text) is
  'Approve or decline time off, recording who and when. A decline needs a '
  'reason. Never moves work that is already booked — that is a separate '
  'decision.';

-- ===========================================================
-- 0025_consumables.sql
-- ===========================================================
-- 0025 Consumables: what a pack is, and where its cost lands
--
-- The schema had two kinds of thing: counted stock and serialised assets. A
-- box of contractor bags is neither. It is counted like stock but it travels
-- and gets used up like equipment, and nobody on a crew can tell you how many
-- bags are left in the box.
--
-- Three modes, one column:
--
--   single_use  masks, gloves, coveralls     counted out, costed to the job
--   bulk        bags, poly sheeting, chemical one container, opened once,
--                                            cost split across what it served
--   returnable  cords, buckets               counted out, counted back, costs
--                                            nothing because it comes home
--
-- THREE ASSUMPTIONS ARE BAKED IN HERE. They were open questions; they are
-- answered this way because the alternatives produce numbers that are not
-- true. Say so and they change — each is a small migration, not a rewrite.
--
--   1. A pack is open or finished. There is no part-used state and no "how
--      full is it" prompt. That question produces a guess, and the whole
--      reason for the pack model is to stop asking it.
--
--   2. PPE is costed to the job, never to the person. What a coverall cost
--      belongs on the job's margin. Who wore it is a payroll and safety
--      question that this app is not the place for.
--
--   3. A pack lives at a stock location — in practice a van — and can be
--      moved. "Which van has an open box of bags" is the question actually
--      asked on a Tuesday morning.

create type consumption_mode as enum ('single_use', 'bulk', 'returnable');

alter table inventory_items
  add column if not exists consumption_mode consumption_mode not null default 'single_use';

comment on column inventory_items.consumption_mode is
  'How this item is consumed: counted per job, opened as a pack, or returned.';

-- ---------------------------------------------------------------------------
-- Open packs
-- ---------------------------------------------------------------------------

create table stock_packs (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references organizations(id) on delete cascade,
  item_id uuid not null references inventory_items(id),
  -- Where the physical container is right now.
  location_id uuid not null references stock_locations(id),
  opened_at timestamptz not null default now(),
  opened_by uuid references profiles(id),
  -- What the container cost, snapshotted when it came off the shelf. The
  -- item's average cost moves with every receipt; this one must not, or a
  -- pack opened in March gets re-costed in July.
  unit_cost numeric(12,4) not null default 0,
  finished_at timestamptz,
  finished_by uuid references profiles(id),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index on stock_packs (org_id, location_id) where finished_at is null;
create index on stock_packs (item_id);

-- Which jobs a pack served. Append-only: a job that used a pack used it, and
-- un-saying that later would quietly move money between jobs.
create table stock_pack_jobs (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references organizations(id) on delete cascade,
  pack_id uuid not null references stock_packs(id) on delete cascade,
  job_id uuid not null references jobs(id) on delete cascade,
  first_used_at timestamptz not null default now(),
  logged_by uuid references profiles(id),
  unique (pack_id, job_id)
);

create index on stock_pack_jobs (job_id);

select attach_updated_at('stock_packs');
select enable_rls('stock_packs');
select enable_rls('stock_pack_jobs');

create policy stock_packs_select on stock_packs for select
  using (org_id = auth_org_id());
create policy stock_packs_write on stock_packs for all
  using (org_id = auth_org_id() and has_permission('inventory.log_usage'))
  with check (org_id = auth_org_id() and has_permission('inventory.log_usage'));

-- Append-only, like every other history table here.
create policy stock_pack_jobs_select on stock_pack_jobs for select
  using (org_id = auth_org_id());
create policy stock_pack_jobs_insert on stock_pack_jobs for insert
  with check (org_id = auth_org_id() and has_permission('inventory.log_usage'));

select attach_audit('stock_packs');

-- ---------------------------------------------------------------------------
-- Opening, using, finishing
-- ---------------------------------------------------------------------------

-- Opening a pack is the moment the stock leaves the shelf. One movement, no
-- job attached — which job pays is not known yet and pretending otherwise is
-- how the first job to touch a box ends up wearing all of it.
create or replace function open_pack(
  p_item_id uuid,
  p_location_id uuid,
  p_job_id uuid default null,
  p_notes text default null
)
returns stock_packs
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_org uuid := auth_org_id();
  v_item inventory_items;
  v_pack stock_packs;
  v_on_hand numeric;
begin
  if not has_permission('inventory.log_usage') then
    raise exception 'Not permitted: opening a pack needs inventory.log_usage'
      using errcode = '42501';
  end if;

  select * into v_item from inventory_items
   where id = p_item_id and org_id = v_org and deleted_at is null;
  if not found then
    raise exception 'No such item' using errcode = '02000';
  end if;
  if v_item.consumption_mode <> 'bulk' then
    raise exception '% is not something you open — it is counted out', v_item.name
      using errcode = '22023';
  end if;

  select coalesce(quantity, 0) into v_on_hand from stock_levels
   where item_id = p_item_id and location_id = p_location_id;
  if coalesce(v_on_hand, 0) < 1 then
    raise exception 'No % left at that location to open', v_item.name
      using errcode = '23514';
  end if;

  insert into stock_packs (org_id, item_id, location_id, opened_by, unit_cost, notes)
  values (v_org, p_item_id, p_location_id, auth_user_id(), v_item.average_cost,
          nullif(btrim(coalesce(p_notes, '')), ''))
  returning * into v_pack;

  insert into stock_movements (
    org_id, item_id, kind, from_location_id, quantity, unit_cost,
    reference_table, reference_id, reason, created_by
  ) values (
    v_org, p_item_id, 'usage', p_location_id, 1, v_item.average_cost,
    'stock_packs', v_pack.id, 'Pack opened', auth_user_id()
  );

  if p_job_id is not null then
    perform use_pack_on_job(v_pack.id, p_job_id);
  end if;

  return v_pack;
end;
$fn$;

comment on function open_pack(uuid, uuid, uuid, text) is
  'Takes one container off the shelf and starts a pack. The cost parks on the '
  'pack until it is finished, because which jobs pay is not known yet.';

-- Says this job used that pack. Cheap, idempotent, and the only thing the
-- crew are ever asked about a pack.
create or replace function use_pack_on_job(p_pack_id uuid, p_job_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $fn$
declare v_pack stock_packs;
begin
  if not has_permission('inventory.log_usage') then
    raise exception 'Not permitted: logging use needs inventory.log_usage'
      using errcode = '42501';
  end if;

  select * into v_pack from stock_packs
   where id = p_pack_id and org_id = auth_org_id();
  if not found then
    raise exception 'No such pack' using errcode = '02000';
  end if;
  if v_pack.finished_at is not null then
    raise exception 'That pack was finished on %', v_pack.finished_at::date
      using errcode = '22023';
  end if;

  insert into stock_pack_jobs (org_id, pack_id, job_id, logged_by)
  values (v_pack.org_id, p_pack_id, p_job_id, auth_user_id())
  on conflict (pack_id, job_id) do nothing;
end;
$fn$;

-- Finishing is the only quantity judgement anyone makes about a pack, and it
-- is a yes/no one: is it empty. That splits its cost across what it served.
create or replace function finish_pack(p_pack_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_pack stock_packs;
  v_jobs int;
begin
  if not has_permission('inventory.log_usage') then
    raise exception 'Not permitted: finishing a pack needs inventory.log_usage'
      using errcode = '42501';
  end if;

  select * into v_pack from stock_packs
   where id = p_pack_id and org_id = auth_org_id();
  if not found then
    raise exception 'No such pack' using errcode = '02000';
  end if;
  if v_pack.finished_at is not null then
    raise exception 'That pack is already finished' using errcode = '22023';
  end if;

  update stock_packs
     set finished_at = now(), finished_by = auth_user_id()
   where id = p_pack_id
   returning * into v_pack;

  select count(*) into v_jobs from stock_pack_jobs where pack_id = p_pack_id;

  return jsonb_build_object(
    'pack_id', p_pack_id,
    'jobs', v_jobs,
    'cost', v_pack.unit_cost,
    -- A pack nobody logged against a job costs the business, not a job. That
    -- is worth seeing rather than silently absorbing.
    'each', case when v_jobs > 0 then round(v_pack.unit_cost / v_jobs, 2) else null end
  );
end;
$fn$;

comment on function finish_pack(uuid) is
  'Marks a pack empty. Its cost then splits evenly across the jobs it served; '
  'a pack logged against no job lands on the business rather than a job.';

create or replace function move_pack(p_pack_id uuid, p_location_id uuid)
returns stock_packs
language plpgsql
security definer
set search_path = public
as $fn$
declare v_pack stock_packs;
begin
  if not has_permission('inventory.transfer') then
    raise exception 'Not permitted: moving stock needs inventory.transfer'
      using errcode = '42501';
  end if;

  update stock_packs
     set location_id = p_location_id
   where id = p_pack_id and org_id = auth_org_id() and finished_at is null
   returning * into v_pack;

  if not found then
    raise exception 'No open pack of that id here' using errcode = '02000';
  end if;
  return v_pack;
end;
$fn$;

-- ---------------------------------------------------------------------------
-- Where the cost lands
-- ---------------------------------------------------------------------------

-- An even split across the jobs a finished pack served. An open pack costs
-- nothing yet, because how many jobs it will serve is not known — and a
-- number that changes every week is not a cost, it is a rumour.
create or replace function job_pack_cost(p_job_id uuid)
returns numeric
language sql
stable
as $fn$
  select coalesce(sum(p.unit_cost / greatest(n.jobs, 1)), 0)
  from stock_pack_jobs pj
  join stock_packs p on p.id = pj.pack_id
  join lateral (
    select count(*) as jobs from stock_pack_jobs x where x.pack_id = p.id
  ) n on true
  where pj.job_id = p_job_id
    and p.finished_at is not null;
$fn$;

comment on function job_pack_cost(uuid) is
  'This job''s share of every finished pack it used. Derived, never stored.';

-- Folded into the materials line rather than added as a seventh column: a
-- pack is materials, and the costing screens and the export keep their shape.
create or replace function job_material_cost(p_job_id uuid)
returns numeric
language sql
stable
as $fn$
  select
    coalesce((
      select sum(mu.quantity * i.average_cost)
      from material_usage mu
      join inventory_items i on i.id = mu.item_id
      where mu.job_id = p_job_id
    ), 0)
    + job_pack_cost(p_job_id);
$fn$;

comment on function job_material_cost(uuid) is
  'Counted materials logged against the job, plus its share of any finished '
  'pack that served it.';

-- ---------------------------------------------------------------------------
-- What is open, and where
-- ---------------------------------------------------------------------------

create view open_packs
with (security_invoker = true)
as
select
  p.id as pack_id,
  p.org_id,
  p.item_id,
  i.sku,
  i.name,
  p.location_id,
  loc.name as location_name,
  p.opened_at,
  p.opened_by,
  p.unit_cost,
  p.notes,
  (select count(*) from stock_pack_jobs pj where pj.pack_id = p.id) as jobs_served
from stock_packs p
join inventory_items i on i.id = p.item_id
join stock_locations loc on loc.id = p.location_id
where p.finished_at is null;

comment on view open_packs is
  'Every container currently open, and which van it is on.';

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'grant select on open_packs to authenticated';
  end if;
end $$;

-- ===========================================================
-- 0026_purchasing.sql
-- ===========================================================
-- 0026 Raising a purchase request, and approving part of one
--
-- Two problems with what was here.
--
-- First, there was no way to raise a request in one go. A client had to
-- insert the request, then its lines, then submit — three writes in an order
-- the lock trigger cares about, and a tab closed in the middle leaves an
-- empty draft nobody will ever find.
--
-- Second, and worse: the approval threshold was checked against the whole
-- request even when the approver had unticked lines. A manager with a $500
-- limit looking at a $900 request could untick the $600 item, leaving $300 —
-- and still be refused. The limit is about what is being spent, so it has to
-- be measured against what is actually being approved.

-- ---------------------------------------------------------------------------
-- The lock was too wide to let anyone approve anything
-- ---------------------------------------------------------------------------
--
-- Lines were frozen outright once a request left draft, which is right for
-- the person who raised it — what was asked for must not change quietly after
-- somebody has looked at it. But approving a request *is* writing to its
-- lines: line_status and rejection_reason live there. So the approve path
-- could never have worked, and receiving a delivered line could not either.
--
-- The rule is really about the ask, not the row: what was requested is
-- frozen; what happened to it afterwards is not.
create or replace function purchase_request_lock_check()
returns trigger
language plpgsql
as $fn$
declare v_status purchase_status;
begin
  select r.status into v_status
    from purchase_requests r
   where r.id = coalesce(new.request_id, old.request_id);

  -- While it is still being written, anything goes.
  if v_status in ('draft', 'under_review') then
    return coalesce(new, old);
  end if;

  -- After that, the decision and the receipt may be recorded; the ask may not
  -- be rewritten, and lines may not appear or vanish.
  if tg_op = 'UPDATE'
     and new.item_id is not distinct from old.item_id
     and new.description is not distinct from old.description
     and new.quantity is not distinct from old.quantity
     and new.unit is not distinct from old.unit
     and new.estimated_unit_cost is not distinct from old.estimated_unit_cost then
    return new;
  end if;

  raise exception 'What was asked for cannot change once the request is submitted'
    using errcode = '23514';
end;
$fn$;

-- What this decision would actually commit to.
create or replace function purchase_request_selected_total(
  p_request_id uuid,
  p_line_ids uuid[] default null
)
returns numeric
language sql
stable
as $fn$
  select coalesce(sum(l.quantity * coalesce(l.estimated_unit_cost, 0)), 0)
  from purchase_request_lines l
  where l.request_id = p_request_id
    and (p_line_ids is null or l.id = any (p_line_ids));
$fn$;

comment on function purchase_request_selected_total(uuid, uuid[]) is
  'The total of the lines actually being approved. A null line list means all '
  'of them.';

create or replace function decide_purchase_request(
  p_request_id uuid,
  p_approve boolean,
  p_reason text default null,
  p_approved_line_ids uuid[] default null
)
returns purchase_requests
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_request purchase_requests;
  v_total numeric;
  v_threshold numeric;
  v_approved_count int;
begin
  select * into v_request from purchase_requests
   where id = p_request_id and org_id = auth_org_id()
   for update;
  if not found then
    raise exception 'No such request' using errcode = '02000';
  end if;
  if v_request.status not in ('submitted', 'under_review') then
    raise exception 'That request is % and cannot be decided now', v_request.status
      using errcode = '22023';
  end if;

  if not has_permission('purchase.approve') then
    raise exception 'Not permitted: approving a purchase needs purchase.approve'
      using errcode = '42501';
  end if;

  if not p_approve and (p_reason is null or btrim(p_reason) = '') then
    raise exception 'Say why, so they know whether to ask differently'
      using errcode = '22023';
  end if;

  -- The threshold is read server-side, never sent by the client, and measured
  -- against the lines being approved rather than everything asked for.
  select coalesce((settings ->> 'approval_threshold')::numeric, 0)
    into v_threshold
    from organizations where id = v_request.org_id;

  v_total := purchase_request_selected_total(p_request_id, p_approved_line_ids);

  if p_approve
     and v_total > v_threshold
     and not has_permission('purchase.approve_unlimited') then
    raise exception
      'That comes to %, over the % you can approve. Take a line off, or send it to the owner.',
      to_char(v_total, 'FM999,999,990.00'), to_char(v_threshold, 'FM999,999,990.00')
      using errcode = '42501';
  end if;

  if p_approve then
    if p_approved_line_ids is null then
      update purchase_request_lines set line_status = 'approved' where request_id = p_request_id;
    else
      update purchase_request_lines
         set line_status = (case when id = any (p_approved_line_ids) then 'approved' else 'rejected' end)::purchase_line_status,
             rejection_reason = case when id = any (p_approved_line_ids) then null else p_reason end
       where request_id = p_request_id;
    end if;

    select count(*) into v_approved_count
      from purchase_request_lines
     where request_id = p_request_id and line_status = 'approved';

    if v_approved_count = 0 then
      raise exception 'Nothing is ticked — reject the request instead'
        using errcode = '22023';
    end if;
  else
    update purchase_request_lines
       set line_status = 'rejected', rejection_reason = p_reason
     where request_id = p_request_id;
  end if;

  update purchase_requests
     set status = case when p_approve then 'approved' else 'rejected' end::purchase_status,
         decided_by = auth_user_id(),
         decided_at = now(),
         decision_reason = nullif(btrim(coalesce(p_reason, '')), '')
   where id = p_request_id
   returning * into v_request;

  return v_request;
end;
$fn$;

comment on function decide_purchase_request(uuid, boolean, text, uuid[]) is
  'Approve all or some lines, or reject with a reason. The spend limit is '
  'measured against the lines being approved, not against everything asked '
  'for.';

-- ---------------------------------------------------------------------------
-- Raising one
-- ---------------------------------------------------------------------------

create or replace function create_purchase_request(
  p_lines jsonb,
  p_job_id uuid default null,
  p_assigned_to uuid default null,
  p_needed_by date default null,
  p_notes text default null,
  p_supplier_id uuid default null,
  p_submit boolean default true
)
returns purchase_requests
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_org uuid := auth_org_id();
  v_request purchase_requests;
  v_line jsonb;
begin
  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'A request with nothing on it is not a request'
      using errcode = '22023';
  end if;

  insert into purchase_requests (
    org_id, requested_by, assigned_to, job_id, needed_by, notes, supplier_id
  ) values (
    v_org, auth_user_id(), p_assigned_to, p_job_id, p_needed_by,
    nullif(btrim(coalesce(p_notes, '')), ''), p_supplier_id
  )
  returning * into v_request;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    if coalesce(btrim(v_line ->> 'description'), '') = '' then
      raise exception 'Every line needs to say what it is' using errcode = '22023';
    end if;
    if coalesce((v_line ->> 'quantity')::numeric, 0) <= 0 then
      raise exception 'Every line needs a quantity' using errcode = '22023';
    end if;

    insert into purchase_request_lines (
      org_id, request_id, item_id, description, quantity, unit, estimated_unit_cost
    ) values (
      v_org, v_request.id,
      nullif(v_line ->> 'item_id', '')::uuid,
      btrim(v_line ->> 'description'),
      (v_line ->> 'quantity')::numeric,
      coalesce(nullif(btrim(coalesce(v_line ->> 'unit', '')), ''), 'each'),
      nullif(v_line ->> 'estimated_unit_cost', '')::numeric
    );
  end loop;

  -- Lines go on while it is still a draft, because the lock trigger stops a
  -- submitted request growing quietly after someone has looked at it.
  if p_submit then
    perform submit_purchase_request(v_request.id);
  end if;

  select * into v_request from purchase_requests where id = v_request.id;
  return v_request;
end;
$fn$;

comment on function create_purchase_request(jsonb, uuid, uuid, date, text, uuid, boolean) is
  'Raises a request with its lines and submits it, in one transaction — so a '
  'closed tab cannot leave an empty draft behind.';

commit;
