#!/usr/bin/env bash
# Concatenates the migrations added since a given one into a single file, so a
# database that is already running an older version can be brought up to date
# with one paste into the Supabase SQL editor.
#
#   ./scripts/build-update.sh 0021                             # -> supabase/update.sql
#   ./scripts/build-update.sh 0026 supabase/update-0027.sql    # a named catch-up
#
# Regenerate after adding a migration; never edit the output by hand.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AFTER="${1:?usage: build-update.sh <last-migration-number-already-applied> [out]}"
OUT="${2:+${ROOT}/${2#"${ROOT}/"}}"
OUT="${OUT:-${ROOT}/supabase/update.sql}"

FILES=()
for f in "${ROOT}"/supabase/migrations/*.sql; do
  n="$(basename "$f" | cut -c1-4)"
  if [[ "$n" > "$AFTER" ]]; then FILES+=("$f"); fi
done

if [ ${#FILES[@]} -eq 0 ]; then
  echo "Nothing after ${AFTER}." >&2
  exit 1
fi

# Whether a second run would stop on something that already exists. A bundle
# that only replaces functions and policies is safe to paste twice, and saying
# "run this once" about one of those makes a person afraid of the safe path.
if grep -qiE '^[[:space:]]*create (table|type|extension)[[:space:]]' "${FILES[@]}"; then
  CREATES=yes
else
  CREATES=no
fi

{
  echo "-- Promold — catch-up from ${AFTER}"
  echo "-- GENERATED by scripts/build-update.sh. Do not edit."
  echo "--"
  echo "-- Paste into the Supabase SQL editor and run, on a database that is"
  echo "-- already at ${AFTER}."
  if [ "$CREATES" = yes ]; then
    echo "--"
    echo "-- Run this ONCE. It is not safe to run twice: it creates tables"
    echo "-- and types, and the second run will stop on the first one that"
    echo "-- already exists. That is deliberate — stopping is better than half"
    echo "-- applying."
  else
    echo "--"
    echo "-- Safe to run more than once: this bundle only replaces functions,"
    echo "-- policies and grants. Nothing in it creates a table or a type."
  fi
  echo "--"
  echo "-- Contains, in order:"
  for f in "${FILES[@]}"; do echo "--   $(basename "$f")"; done
  echo "-- Generated from $(cd "$ROOT" && git rev-parse --short HEAD 2>/dev/null || echo 'working tree')"
  echo
  echo "begin;"
  echo
  for f in "${FILES[@]}"; do
    echo "-- ==========================================================="
    echo "-- $(basename "$f")"
    echo "-- ==========================================================="
    cat "$f"
    echo
  done
  echo
  echo "-- ==========================================================="
  echo "-- Did it land?"
  echo "-- ==========================================================="
  echo "-- Printed by the same transaction that applied it, so there is no"
  echo "-- second round trip to find out whether it worked."
  echo "select 'Applied' as result,"
  echo "  (select count(*) from pg_proc where proname = 'set_job_price') > 0 as price_guard_0027,"
  echo "  (select count(*) from information_schema.tables"
  echo "    where table_schema = 'public') as tables,"
  echo "  (select count(*) from pg_policies where schemaname = 'public') as policies;"
  echo
  echo "commit;"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines, ${#FILES[@]} migrations)"
