#!/usr/bin/env bash
# Concatenates the migrations added since a given one into a single file, so a
# database that is already running an older version can be brought up to date
# with one paste into the Supabase SQL editor.
#
#   ./scripts/build-update.sh 0021     # everything after 0021
#
# Regenerate after adding a migration; never edit the output by hand.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AFTER="${1:?usage: build-update.sh <last-migration-number-already-applied>}"
OUT="${ROOT}/supabase/update.sql"

FILES=()
for f in "${ROOT}"/supabase/migrations/*.sql; do
  n="$(basename "$f" | cut -c1-4)"
  if [[ "$n" > "$AFTER" ]]; then FILES+=("$f"); fi
done

if [ ${#FILES[@]} -eq 0 ]; then
  echo "Nothing after ${AFTER}." >&2
  exit 1
fi

{
  echo "-- Promold — catch-up from ${AFTER}"
  echo "-- GENERATED by scripts/build-update.sh. Do not edit."
  echo "--"
  echo "-- Run this ONCE, in the Supabase SQL editor, on a database that is"
  echo "-- already at ${AFTER}. It is not safe to run twice: it creates tables"
  echo "-- and types, and the second run will stop on the first one that"
  echo "-- already exists. That is deliberate — stopping is better than half"
  echo "-- applying."
  echo "--"
  echo "-- Contains, in order:"
  for f in "${FILES[@]}"; do echo "--   $(basename "$f")"; done
  echo "-- Generated from $(cd "$ROOT" && git rev-parse --short HEAD 2>/dev/null || echo 'working tree')"
  echo
  echo "begin;"
  echo
  for f in "${FILES[@]}"; do
    echo "-- ==========================================================="
    echo "-- $(basename "$f")"
    echo "-- ==========================================================="
    cat "$f"
    echo
  done
  echo "commit;"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines, ${#FILES[@]} migrations)"
