#!/usr/bin/env bash
# Concatenates every migration into one file that can be pasted into the
# Supabase SQL editor, so a new project can be set up without installing the
# CLI. Regenerate after any schema change; never edit the output by hand.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/supabase/bootstrap.sql"

{
  echo "-- Promold — full schema bootstrap"
  echo "-- GENERATED by scripts/build-bootstrap.sh. Do not edit."
  echo "-- Source: supabase/migrations/*.sql, in order."
  echo "-- Generated from $(cd "$ROOT" && git rev-parse --short HEAD 2>/dev/null || echo 'working tree')"
  echo
  echo "-- Paste into the Supabase SQL editor and run once. See"
  echo "-- docs/SUPABASE-SETUP.md for the rest of the steps."
  echo
  for f in "${ROOT}"/supabase/migrations/*.sql; do
    echo "-- ==========================================================="
    echo "-- $(basename "$f")"
    echo "-- ==========================================================="
    cat "$f"
    echo
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
